let preloadedImages = new Array();

function preload(imgUrlArray) {
    for (var i = 0; i < imgUrlArray.length; i++) {
        preloadedImages[i] = new Image();
        preloadedImages[i].src = imgUrlArray[i];
    }
}

preload([
    "./src/img/attackerIcon/sledge.png", //attacker
    "./src/img/attackerIcon/thatcher.png",
    "./src/img/attackerIcon/ash.png",
    "./src/img/attackerIcon/thermite.png",
    "./src/img/attackerIcon/twitch.png",
    "./src/img/attackerIcon/montagne.png",
    "./src/img/attackerIcon/glaz.png",
    "./src/img/attackerIcon/fuze.png",
    "./src/img/attackerIcon/blitz.png",
    "./src/img/attackerIcon/iq.png",
    "./src/img/attackerIcon/buck.png",
    "./src/img/attackerIcon/blackbeard.png",
    "./src/img/attackerIcon/capitao.png",
    "./src/img/attackerIcon/hibana.png",
    "./src/img/attackerIcon/jackal.png",
    "./src/img/attackerIcon/ying.png",
    "./src/img/attackerIcon/zofia.png",
    "./src/img/attackerIcon/dokkaebi.png",
    "./src/img/attackerIcon/lion.png",
    "./src/img/attackerIcon/finka.png",
    "./src/img/attackerIcon/maverick.png",
    "./src/img/attackerIcon/nomad.png",
    "./src/img/attackerIcon/gridlock.png",
    "./src/img/attackerIcon/nokk.png",
    "./src/img/attackerIcon/amaru.png",
    "./src/img/attackerIcon/kali.png",
    "./src/img/attackerIcon/iana.png",
    "./src/img/attackerIcon/ace.png",
    "./src/img/attackerIcon/zero.png",
    "./src/img/attackerIcon/flores.png",
    "./src/img/defenderIcon/smoke.png", //defender
    "./src/img/defenderIcon/mute.png",
    "./src/img/defenderIcon/castle.png",
    "./src/img/defenderIcon/pulse.png",
    "./src/img/defenderIcon/doc.png",
    "./src/img/defenderIcon/rook.png",
    "./src/img/defenderIcon/kapkan.png",
    "./src/img/defenderIcon/tachanka.png",
    "./src/img/defenderIcon/jager.png",
    "./src/img/defenderIcon/bandit.png",
    "./src/img/defenderIcon/frost.png",
    "./src/img/defenderIcon/valkyrie.png",
    "./src/img/defenderIcon/caveira.png",
    "./src/img/defenderIcon/echo.png",
    "./src/img/defenderIcon/mira.png",
    "./src/img/defenderIcon/lesion.png",
    "./src/img/defenderIcon/ela.png",
    "./src/img/defenderIcon/vigil.png",
    "./src/img/defenderIcon/maestro.png",
    "./src/img/defenderIcon/alibi.png",
    "./src/img/defenderIcon/clash.png",
    "./src/img/defenderIcon/kaid.png",
    "./src/img/defenderIcon/mozzie.png",
    "./src/img/defenderIcon/warden.png",
    "./src/img/defenderIcon/goyo.png",
    "./src/img/defenderIcon/wamai.png",
    "./src/img/defenderIcon/oryx.png",
    "./src/img/defenderIcon/melusi.png",
    "./src/img/defenderIcon/aruni.png",
    "./src/img/defenderIcon/thunderbird.png",
    "./src/img/defenderIcon/thorn.png",
    "./src/img/gadgetIcon/alarm.jpg", //gadget
    "./src/img/gadgetIcon/barricade.jpg",
    "./src/img/gadgetIcon/bleaching.jpg",
    "./src/img/gadgetIcon/c4.jpg",
    "./src/img/gadgetIcon/camera.jpg",
    "./src/img/gadgetIcon/claymore.jpg",
    "./src/img/gadgetIcon/diffuser.jpg",
    "./src/img/gadgetIcon/drone.jpg",
    "./src/img/gadgetIcon/flash.jpg",
    "./src/img/gadgetIcon/grenade.jpg",
    "./src/img/gadgetIcon/hardbleaching.jpg",
    "./src/img/gadgetIcon/impact.jpg",
    "./src/img/gadgetIcon/reinforcement.jpg",
    "./src/img/gadgetIcon/shield.jpg",
    "./src/img/gadgetIcon/smoke.jpg",
    "./src/img/gadgetIcon/wire.jpg",
    "./src/img/mapImg/bank/bank1f.png",
    "./src/img/mapImg/bank/bank2f.png",
    "./src/img/mapImg/bank/bankb1f.png",
    "./src/img/mapImg/chalet/chalet1f.png",
    "./src/img/mapImg/chalet/chalet2f.png",
    "./src/img/mapImg/chalet/chaletb1f.png",
    "./src/img/mapImg/clubhouse/clubhouse1f.png",
    "./src/img/mapImg/clubhouse/clubhouse2f.png",
    "./src/img/mapImg/clubhouse/clubhouseb1f.png",
    "./src/img/mapImg/coastline/coastline1f.png",
    "./src/img/mapImg/coastline/coastline2f.png",
    "./src/img/mapImg/kafe/kafe1f.png",
    "./src/img/mapImg/kafe/kafe2f.png",
    "./src/img/mapImg/kafe/kafe3f.png",
    "./src/img/mapImg/oregon/oregon1f.png",
    "./src/img/mapImg/oregon/oregon2f.png",
    "./src/img/mapImg/oregon/oregonb1f.png",
    "./src/img/mapImg/villa/villa1f.png",
    "./src/img/mapImg/villa/villa2f.png",
    "./src/img/mapImg/villa/villab1f.png",
]);